[project]
name = "pixel-native-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "pillow>=12.3.0",
    "protobuf>=7.36.1",
    "pymupdf>=1.28.2",
    "pytesseract>=0.3.13",
    "rank-bm25>=0.2.2",
    "sentencepiece>=0.2.2",
    "torch>=2.14.0",
    "transformers>=5.16.1",
]
